STAGE_W = 800*3/4;
STAGE_H = 600*3/4;

DEBUG_MODE = true;
DEBUG_INPUT = false;
DEBUG_FPS = false;

MAX_DELTA = 1/30.0;

KEYS_UP = [38,87];
KEYS_DOWN = [40, 83];
KEYS_LEFT = [37, 65];
KEYS_RIGHT = [39, 68];

PLAYER_SPEED = 222;

OBJECT_SCALE = 3;

OBSTACLE_EXPLODE_TIME = .5;
OBSTACLE_EDGE_CLEARANCE = 50;

DEPTH_SCALE = true;
DEPTH_SCALE_MIN = .75;
DEPTH_SCALE_MAX = 2;

DIAG = Math.sqrt(2);

DEFAULT_BACKGROUND_COLOR = 0xe0ffff;
IMAGE_PATH = "/img/";